# Generated by Django 5.0.6 on 2024-07-19 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0011_alter_driver_emerg_cont_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter number in the correct format starting with 254 or 01(Upto to 10 digits)', regex='^(?:\\+254|254|0)((1|7)(?:(?:[0–9][0–9])|(?:[0–9][0–9][0–9]))[0–9]{6}$')], verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('payment', models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent')], max_length=255)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='booking.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
