# Generated by Django 5.0.6 on 2024-07-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('bus_manager', 'Bus_Manager'), ('admin', 'Admin')], max_length=255),
        ),
    ]
