# Generated by Django 5.0.6 on 2024-07-20 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter number in the correct format starting with 254 or 01(Upto to 10 digits)', regex='^(?:\\+254|254|0)((1|7)(?:(?:[0-9][0-9])|(?:[0-9][0-9][0-9]))[0-9]{6})$')], verbose_name='Phone number'),
        ),
    ]
