# Generated by Django 5.0.6 on 2024-07-11 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='route_pictures/')),
                ('starting_location', models.CharField(max_length=255)),
                ('final_destination', models.CharField(max_length=255)),
                ('depature_date', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('distance_covered', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254123456789 or +254 123 456 789 (up to 10 digits).', regex='^(\\+254)?[ ]?[7]{1}([0-9]{1})([0-9]{1})[ ]?[0-9]{3}[ ]?[0-9]{3}$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
                ('principal_name', models.CharField(max_length=255)),
                ('students_count', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_number', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254123456789 or +254 123 456 789 (up to 10 digits).', regex='^(\\+254)?[ ]?[7]{1}([0-9]{1})([0-9]{1})[ ]?[0-9]{3}[ ]?[0-9]{3}$')], verbose_name='Phone number')),
                ('image', models.ImageField(upload_to='driver_pictures/')),
                ('email_address', models.EmailField(max_length=254)),
                ('emerg_cont_name', models.CharField(max_length=200)),
                ('emerg_cont_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254123456789 or +254 123 456 789 (up to 10 digits).', regex='^(\\+254)?[ ]?[7]{1}([0-9]{1})([0-9]{1})[ ]?[0-9]{3}[ ]?[0-9]{3}$')], verbose_name='Phone number')),
                ('employment_date', models.DateField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='school',
            field=models.ManyToManyField(to='booking.school'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.school')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Debit Card', 'debit card'), ('Credit Card', 'credit card'), ('Mpesa', 'mpesa')], max_length=255)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users'),
        ),
    ]
