# Generated by Django 5.0.6 on 2024-07-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='depature_date',
            new_name='departure_date',
        ),
    ]
