# Generated by Django 5.0.6 on 2024-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_depature_date_route_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.ManyToManyField(to='booking.route'),
        ),
    ]
