# Generated by Django 5.0.6 on 2024-07-13 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_school_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254123456789 or +254 123 456 789 (up to 10 digits).', regex='^\\+254\\s?[7|0][0-9]{2}\\s?[0-9]{3}\\s?[0-9]{3}$')], verbose_name='Phone number'),
        ),
    ]
