# Generated by Django 5.0.6 on 2024-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_school_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cost',
            field=models.CharField(max_length=15),
        ),
    ]
