# Generated by Django 5.0.6 on 2024-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_payment_user_alter_booking_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_pictures/'),
        ),
    ]
