# Generated by Django 5.0.6 on 2024-07-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_seat_booked_by_seat_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='payment_status',
        ),
    ]
