# Generated by Django 5.0.6 on 2024-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rename_status_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr/'),
        ),
    ]
