# Generated by Django 5.0.6 on 2024-07-29 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254123456789 or +254 123 456 789 (up to 10 digits).', regex='^(\\+254)?[ ]?[7]{1}([0-9]{1})([0-9]{1})[ ]?[0-9]{3}[ ]?[0-9]{3}$')], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='Pending', max_length=100),
        ),
    ]
